name: Deploy API to Render

on:
  push:
    branches:
      - main
      - master
      - 'claude/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check configuration
        run: echo "Checking Render configuration..."

      - name: Deploy
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            echo "[SKIP] RENDER_DEPLOY_HOOK_URL not configured"
            echo "To enable deployment, add RENDER_DEPLOY_HOOK_URL secret"
            exit 0
          fi
          echo "Deploying to Render..."
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
          echo "[OK] Deployment triggered"
