name: Deploy Gradio to Hugging Face Spaces

on:
  push:
    branches:
      - main
      - master
      - 'claude/**'  # Allow testing on Claude branches
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push to Hugging Face Space
        if: ${{ secrets.HF_TOKEN }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
        run: |
          # Install git-lfs
          git lfs install

          # Configure git
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Clone HF Space repository
          git clone https://huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME hf-space || \
          (cd hf-space && git init && git remote add origin https://huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME)

          cd hf-space

          # Copy necessary files
          cp -r ../music_rag ../requirements.txt ../README.md .

          # Create app.py for Gradio
          cat > app.py << 'EOF'
          """Hugging Face Spaces Gradio App for Music RAG."""
          import os
          from music_rag.ui.gradio_app import create_interface

          # Get OpenAI key from HF secrets
          openai_key = os.getenv('OPENAI_API_KEY')

          # Create and launch interface
          app = create_interface(
              db_path="./data/chromadb",
              openai_api_key=openai_key
          )

          if __name__ == "__main__":
              app.launch()
          EOF

          # Create README for the Space
          cat > README.md << 'EOF'
          ---
          title: Music RAG
          emoji: 🎵
          colorFrom: indigo
          colorTo: purple
          sdk: gradio
          sdk_version: "4.0.0"
          app_file: app.py
          pinned: false
          ---

          # Music RAG - AI-Powered Music Discovery

          This is a Gradio interface for the Music RAG system, featuring:
          - Dual-track retrieval (broad + targeted)
          - Multimodal embeddings (text + audio)
          - Cross-encoder reranking
          - Query enhancement with LLMs

          ## Configuration

          To enable advanced features, set these secrets in your Space settings:
          - `OPENAI_API_KEY`: For query enhancement and result explanations

          ## Learn More

          Visit the [GitHub repository](https://github.com/${{ github.repository }}) for more information.
          EOF

          # Commit and push
          git add .
          git commit -m "Update from GitHub Actions" || echo "No changes to commit"

          # Push with authentication
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME main || \
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME main --force

      - name: Deployment complete
        run: |
          echo "Gradio app deployed to Hugging Face Spaces"
