name: Test Workflow

on:
  push:
    branches:
      - 'claude/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test step
        run: echo "Workflow is working!"

      - name: List files
        run: ls -la docs/
